### ISSUE TITLE
 python django installation problem #3

### ISSUE THREAD

**Issue by freeroute** [Subterfuge-Framework/Subterfuge#10]
When run subterfuge I got this error. What is the problem? Could you help me, please?

root@freeroute:~/Downloads/Subterfuge# subterfuge 
Traceback (most recent call last):
  File "/bin/subterfuge", line 25, in <module>
    from main.models import *
  File "/usr/share/subterfuge/main/models.py", line 3, in <module>
    class credentials(models.Model):
  File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 94, in **new**
    app_config = apps.get_containing_app_config(module)
  File "/usr/lib/python2.7/dist-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/usr/lib/python2.7/dist-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
root@freeroute:~/Downloads/Subterfuge#

**Comment by ufinal** [comment]
sudo pip install django=="1.5"
reboot now
also remove version higher then 1.5

**Comment by dgramop** [comment]
Instead of reboot just stop the service and start ?

**Comment by freeroute** [comment]
Thanks for your help. I have installed django 1.5., now subterfuge running, but login credentials not captured. What sould I check?

**Comment by 0sm0s1z** [comment]
Issue resolved by: 6c35097
