### ISSUE TITLE
Traceback (most recent call last):   File "/bin/subterfuge", line 7, in <module>     from update import updatecheck   File "/usr/share/subterfuge/update.py", line 14, in <module>     c.execute("SELECT autoupdate FROM main_setup") sqlite3.DatabaseError: database disk image is malformed

### ISSUE THREAD

**Issue by shubham399** [Subterfuge-Framework/Subterfuge#13]
Traceback (most recent call last):
  File "/bin/subterfuge", line 7, in <module>
    from update import updatecheck
  File "/usr/share/subterfuge/update.py", line 14, in <module>
    c.execute("SELECT autoupdate FROM main_setup")
sqlite3.DatabaseError: database disk image is malformed

**Comment by 0sm0s1z** [comment]
I'm unable to replicate this issue. Can anyone confirm?
