### ISSUE TITLE
python django installation problem

### ISSUE THREAD

**Issue by Indeserpen** [Subterfuge-Framework/Subterfuge#2]
when runninig ./xsubterfube: 
System check identified some issues:

WARNINGS:
?: (1_6.W001) Some project unittests may not execute as expected.
    HINT: Django 1.6 introduced a new default test runner. It looks like this project was generated using Django 1.5 or earlier. You should ensure your tests are all running & behaving as expected. See https://docs.djangoproject.com/en/dev/releases/1.6/#new-test-runner for more information.

System check identified 1 issue (0 silenced).

You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.

After running commande: python manage.py migrate:
root@kali:~/Subterfuge# python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/**init**.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/**init**.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python2.7/dist-packages/django/conf/**init**.py", line 46, in **getattr**
    self._setup(name)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 98, in **init**
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'subterfuge.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named subterfuge.settings

Subterfuge itself is running 127.0.0.1, but in terminal i can see those errors:

Traceback (most recent call last):
  File "/usr/share/subterfuge/attackctrl.py", line 351, in <module>
    attack(sys.argv[1])
  File "/usr/share/subterfuge/attackctrl.py", line 47, in attack
    autoconfig()
  File "/usr/share/subterfuge/attackctrl.py", line 337, in autoconfig
    setup.objects.update(gateway = autogate)
  File "/usr/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 581, in update
    query.add_update_values(kwargs)
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/subqueries.py", line 129, in add_update_values
    field, model, direct, m2m = self.get_meta().get_field_by_name(name)
  File "/usr/lib/python2.7/dist-packages/django/db/models/options.py", line 416, in get_field_by_name
    cache = self.init_name_map()
  File "/usr/lib/python2.7/dist-packages/django/db/models/options.py", line 445, in init_name_map
    for f, model in self.get_all_related_m2m_objects_with_model():
  File "/usr/lib/python2.7/dist-packages/django/db/models/options.py", line 563, in get_all_related_m2m_objects_with_model
    cache = self._fill_related_many_to_many_cache()
  File "/usr/lib/python2.7/dist-packages/django/db/models/options.py", line 577, in _fill_related_many_to_many_cache
    for klass in self.apps.get_models():
  File "/usr/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(_args, *_kwds)
  File "/usr/lib/python2.7/dist-packages/django/apps/registry.py", line 168, in get_models
    self.check_models_ready()
  File "/usr/lib/python2.7/dist-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.
[21/Aug/2015 04:56:13] "GET /hostcheck/ HTTP/1.1" 200 10415
[21/Aug/2015 04:56:16] "GET /hostcheck/ HTTP/1.1" 200 10415
[21/Aug/2015 04:56:19] "GET /hostcheck/ HTTP/1.1" 200 10415
[21/Aug/2015 04:56:23] "GET /hostcheck/ HTTP/1.1" 200 10415
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
[21/Aug/2015 04:56:23] "GET / HTTP/1.1" 200 21078
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 194, in send_preamble
    'Date: %s\r\n' % format_date_time(time.time())
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
## [21/Aug/2015 04:56:23] "GET /hostcheck/ HTTP/1.1" 500 59

Exception happened during processing of request from ('127.0.0.1', 57746)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
[21/Aug/2015 04:56:23] "GET /static/images/help.png HTTP/1.1" 304 0
[21/Aug/2015 04:56:23] "GET /static/images/menu.png HTTP/1.1" 304 0
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 129, in **init**
    super(WSGIRequestHandler, self).**init**(_args, *_kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 657, in **init**
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
## error: [Errno 32] Broken pipe

[21/Aug/2015 04:56:23] "GET / HTTP/1.1" 200 3457
[21/Aug/2015 04:56:26] "GET / HTTP/1.1" 200 3457
[21/Aug/2015 04:56:29] "GET / HTTP/1.1" 200 3457
[21/Aug/2015 04:56:32] "GET / HTTP/1.1" 200 3457
[21/Aug/2015 04:56:35] "GET / HTTP/1.1" 200 3457

System i,m running is Kali Linux Sana, 64 bit AMD

Thanks!!

**Comment by 0sm0s1z** [comment]
The file xsubterfuge only exists so that the setup script can place it in the syspath. Try executing:

$ python setup.py
$ subterfuge
