### ISSUE TITLE
not collecting any data!

### ISSUE THREAD

**Issue by Indeserpen** [Subterfuge-Framework/Subterfuge#8]
So installed subterfuge, installed django 1.5! when i run subterfuge i get this:
ubterfuge courtesy of r00t0v3rr1d3 & 0sm0s1z
/usr/local/lib/python2.7/dist-packages/django/conf/**init**.py:219: DeprecationWarning: You have no filters defined on the 'mail_admins' logging handler: adding implicit debug-false-only filter. See http://docs.djangoproject.com/en/dev/releases/1.4/#request-exceptions-are-now-always-logged
  DeprecationWarning)

/usr/local/lib/python2.7/dist-packages/django/conf/**init**.py:219: DeprecationWarning: You have no filters defined on the 'mail_admins' logging handler: adding implicit debug-false-only filter. See http://docs.djangoproject.com/en/dev/releases/1.4/#request-exceptions-are-now-always-logged
  DeprecationWarning)

Validating models...

0 errors found
October 20, 2015 - 15:08:56
Django version 1.5, using settings 'subterfuge.settings'
Development server is running at http://127.0.0.1:80/
Quit the server with CONTROL-C.

Subterfuge is not showing any errors, but its also not collecting any data from network!
Start button is diseappering after initalize and in terminal its:
ctober 20, 2015 - 15:08:56
Django version 1.5, using settings 'subterfuge.settings'
Development server is running at http://127.0.0.1:80/
Quit the server with CONTROL-C.
[20/Oct/2015 15:11:17] "GET / HTTP/1.1" 200 21527
[20/Oct/2015 15:11:17] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:11:20] "GET /startpwn/auto/ HTTP/1.1" 200 0
Traceback (most recent call last):
  File "/usr/share/subterfuge/attackctrl.py", line 14, in <module>
    django.setup()
AttributeError: 'module' object has no attribute 'setup'
[20/Oct/2015 15:11:20] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:11:23] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:11:26] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:11:29] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:11:32] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:11:35] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:11:38] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:11:41] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:11:44] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:11:47] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:11:50] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:11:53] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:11:56] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:11:59] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:12:02] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:12:05] "GET / HTTP/1.1" 200 2613
^A[20/Oct/2015 15:12:08] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:12:11] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:12:14] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:12:17] "GET / HTTP/1.1" 200 2613

Here one screen from desktop

![screenshot from 2015-10-20 23 12 34](https://cloud.githubusercontent.com/assets/13330266/10619762/20999c8e-7780-11e5-98ed-6ffb3f01d316.png)

pointed manually to gateway and tried MITMproxy : 
I get this:
No default gw on eth0
No default gw on wlan2
[20/Oct/2015 15:13:48] "GET /settings/ HTTP/1.1" 200 27751
[20/Oct/2015 15:13:48] "GET /static/css/images/ui-bg_glass_75_e6e6e6_1x400.png HTTP/1.1" 404 1725
[20/Oct/2015 15:13:48] "GET /static/css/images/ui-bg_highlight-soft_75_cccccc_1x100.png HTTP/1.1" 404 1752
[20/Oct/2015 15:13:48] "GET /static/css/images/ui-bg_flat_75_ffffff_40x100.png HTTP/1.1" 404 1725
Using Interface => wlan0
Auto Configure  => yes
Using Gateway   => 192.168.0.1
Using Gateway   => mitmproxy
[20/Oct/2015 15:13:57] "POST /config/settings/ HTTP/1.1" 200 26289
[20/Oct/2015 15:14:00] "GET /startpwn/auto/ HTTP/1.1" 200 0
Traceback (most recent call last):
  File "/usr/share/subterfuge/attackctrl.py", line 14, in <module>
    django.setup()
AttributeError: 'module' object has no attribute 'setup'
[20/Oct/2015 15:14:22] "GET / HTTP/1.1" 200 21527
[20/Oct/2015 15:14:22] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:14:25] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:14:28] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:14:29] "GET /startpwn/auto/ HTTP/1.1" 200 0
Traceback (most recent call last):
  File "/usr/share/subterfuge/attackctrl.py", line 14, in <module>
    django.setup()
AttributeError: 'module' object has no attribute 'setup'
[20/Oct/2015 15:14:31] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:14:34] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:14:37] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:14:40] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:14:43] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:14:46] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:14:49] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:14:52] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:14:55] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:14:58] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:15:01] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:15:04] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:15:07] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:15:10] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:15:13] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:15:16] "GET / HTTP/1.1" 200 2613
[20/Oct/2015 15:15:19] "GET / HTTP/1.1" 200 2613

Same thing using sslstrip!

Thanks!

**Comment by freeroute** [comment]
I have the same problem.
root@freeroute:~/Downloads/Subterfuge# python setup.py
[+] Beginning Subterfuge installation...
Hit:4 http://repo.kali.org/kali kali-bleeding-edge InRelease  
Hit:1 http://kali.mirror.garr.it/mirrors/kali kali-rolling InRelease
Hit:2 http://kali.mirror.garr.it/mirrors/kali-security sana/updates InRelease
Hit:3 http://kali.mirror.garr.it/mirrors/kali sana InRelease
Reading package lists... Done  
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Note, selecting 'udhcpd' instead of 'dhcpd'
arptables is already the newest version (0.0.3.4-1).
python-django is already the newest version (1.9.2-1).
python-scapy is already the newest version (2.2.0-1kali1).
python-twisted is already the newest version (15.5.0-4).
udhcpd is already the newest version (1:1.22.0-18).
The following packages were automatically installed and are no longer required:
  libasn1-8-heimdal libgssapi3-heimdal libgstreamer-plugins-base0.10-0 libgstreamer0.10-0 libhcrypto4-heimdal libheimbase1-heimdal libheimntlm0-heimdal libhx509-5-heimdal libilmbase6v5 libkrb5-26-heimdal
  libntdb1 libopenexr6v5 libquvi-scripts libquvi7 libroken18-heimdal libsysfs2 libwind0-heimdal libx265-68 python-ntdb screen
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 37 not upgraded.
[+] Subterfuge installation completed successfully!

And the console messages: 
[05/Mar/2016 08:56:54] "GET /startpwn/regular/ HTTP/1.1" 200 0
Traceback (most recent call last):
  File "/usr/share/subterfuge/attackctrl.py", line 14, in <module>
    django.setup()
AttributeError: 'module' object has no attribute 'setup'
[05/Mar/2016 08:56:55] "GET / HTTP/1.1" 200 2613
[05/Mar/2016 08:56:58] "GET / HTTP/1.1" 200 2613
[05/Mar/2016 08:57:01] "GET / HTTP/1.1" 200 2613
[05/Mar/2016 08:57:04] "GET / HTTP/1.1" 200 2613
[05/Mar/2016 08:57:07] "GET / HTTP/1.1" 200 2613
